<p><?php echo $message ?></p>
<main>

    <h1>Prijavnica za PHP akademiju</h1>

    <p>Prijavnica za prvo osječko izdanje PHP akademije koju Inchoo pokreće u suradnji s FERITom.</p>
    <p>Prijave traju do 10.10., pa požuri i svoje mjesto rezerviraj već sad.</p>
    <p>Više informacija na:
        <a href="http://inchoo.hr/php-akademija-2016/" target="_blank">http://inchoo.hr/php-akademija-2016/</a>
    </p>

    <!-- fix form -->
	
    <form method="post" action="submit" enctype="multipart/form-data">
    <label for="name">Ime i prezime:</label>
    <input id="name" placeholder="npr.Kristina Slović" name="name" required/>

    <label for="email">Mail adresa:</label>
    <input id="email" placeholder="npr. kslovic@etfos.hr "name="email" type="email" required/>

    <label for="smjer">Smjer:</label>
    <input id="smjer" placeholder="npr. Diplomski studij računarstva" name="smjer" required/>

    <label>Godina studija:</label><br>
    <label><input name="godina" type="radio" value="1" checked/>1</label>
    <label><input name="godina" type="radio" value="2"/>2</label>
    <label><input name="godina" type="radio" value="3"/>3</label>
    <label><input name="godina" type="radio" value="4"/>4</label>
    <label><input name="godina" type="radio" value="5"/>5</label>
    
    <label>Što te motiviralo da se prijaviš?</label>
    <textarea name="motivacija"required rows="10" cols="60">

    </textarea>


    <label>Imaš li predznanje vezano uz web development?</label>
    <textarea name="predznanje" required rows="10" cols="60">

    </textarea>

    U kojim jezicima si do sada programirao?
    <label><input name="jezik[]" type="checkbox" value="C"/>C</label>
    <label><input name="jezik[]" type="checkbox" value="C#"/>C#</label>
	<label><input name="jezik[]" type="checkbox" value="C++"/>C++</label>
    <label><input name="jezik[]" type="checkbox" value="Java"/>Java</label><br>
	Uploadaj primjer svoga koda:
    <input type="file" name="code"/>
	 <input type="submit" name="prijava" value="Predaj prijavu"/>
    </form>
</main>
