<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <title>PHP akademija-prijava</title>
    <style>
	
        input[type=text], textarea, label { display: block; }
		main{
			border:5px solid olivedrab;
			border-radius: 25px;
			margin:20px;
			padding:20px;
			color:olivedrab;
			
		}
		 h1{
	color:olivedrab;
	font-size:25px;
		}
		p{
			font-size:17px;
			font-weight: bold;
		}
		ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover {
    background-color: olivedrab;
}
a{
		color:black;
	}
	input[type=submit], input[type=file]{
		background-color:olivedrab;
		color:white;
	}
	input[type=submit]:hover, input[type=file]{
    background-color: yellowgreen;
}
    </style>
</head>
<body>

<header>
    <ul>
        <li><a href="index">Naslovnica</a></li>
        <li><a href="form">Prijavi se</a></li>
        <li><a href="#">Prijavi se(kao admin)</a></li>
    </ul>
</header>
    
<?php echo $content ?>

</body>

</html>
<footer>
    <p>&copy; PHP Akademija, 2016</p>
</footer>