<?php

   if($_FILES['code']['name']) {
$uploadpath = "C:/xampp/htdocs/php-academy/uploads/";
$filename=$_FILES['code']['name'];
$cleanfile=$_FILES['code']['name'];
$temp = explode(".", $_FILES["code"]["name"]);
$newfilename = $_POST['name'] . 'Code.txt';
 if(move_uploaded_file($_FILES["code"]["tmp_name"],  $uploadpath . $newfilename)) {?> <p> <?php echo "Vaš kod je uspješno objavljen!"; ?> </p><br> <?php 
 }
}
if(isset($_POST['name']) && isset($_POST['email'])&& isset($_POST['smjer'])&& isset($_POST['godina'])&& isset($_POST['motivacija'])&& isset($_POST['predznanje'])) {
    $jezici=" ";
	$name=array();
	if(isset($_POST['jezik'])){
		$name = $_POST['jezik'];
		foreach($name as $jezik){
		$jezici.=$jezik ." ";

}
	}
	$myfile = fopen("C:/xampp/htdocs/php-academy/uploads/".$_POST['name'].".txt", "w") or die("Unable to open file!");
	$data ="Ime i prezime:". $_POST['name'] . "\nE-mail:" . $_POST['email'] . "\nSmjer:" . $_POST['smjer'] . "\nGodina:" . $_POST['godina'] . "\nŠto te motiviralo da se prijaviš?" . $_POST['motivacija'] . "\nImaš li predznanje vezano uz web development?" . $_POST['predznanje'] . "\nU kojim jezicima si do sada programirao?" . $jezici;
    $ret = file_put_contents('C:/xampp/htdocs/php-academy/uploads/'.$_POST['name'].'.txt', $data, FILE_APPEND | LOCK_EX);
    if($ret === false) {
        die('There was an error writing this file');
    }
    else {
       header('location:thankyou');
    }
}
else{
	header('location:form');
}

?>